import AccessDenied from "components/AccessDenied";
import Layout from "components/Layout";
import { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";

const Account: NextPage = ({ locations }: any) => {
  const { data: session, status } = useSession();

  // If no session exists, display access denied message
  if (!session) {
    return (
      <Layout>
        <AccessDenied />
      </Layout>
    );
  }

  return (
    <Layout>
      <Head>
        <title>Parkerad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello {session.user?.name}, your account id is{" "}
      <code>{session.user.id}</code>.
      <style global jsx>
        {``}
      </style>
    </Layout>
  );
};

export default Account;
