import type {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Location from "modules/locations/Location";
import Footer from "modules/footer/Footer";
import styles from "styles/Home.module.css";
import prisma from "lib/prisma";

const Home: NextPage = ({
  locations,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  console.log(locations);

  return (
    <div className={styles.container}>
      <Head>
        <title>Parkerad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section id="intro" className={styles.intro}>
        <div className={styles.title}>
          <h1>Parkerad</h1>
          <h2>A very catchy slogan about benches</h2>
        </div>

        <Link href="/#locations">
          <Image
            src="/icons/arrow-down.png"
            width={64}
            height={64}
            alt="down arrow"
            layout="fixed"
            className={styles.downArrow}
          />
        </Link>
      </section>

      <section id="locations" className={styles.locations}>
        <h1>Bänkar</h1>
        <div className={styles.locationList}>
          <Location locations={locations} />
        </div>
      </section>

      <Footer />
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  // await prisma.user.create({
  //   data: {
  //     username: "Snöderlund",
  //   },
  // });

  // await prisma.location.create({
  //   data: {
  //     locationName: "Trippeln",
  //     description: "Tre bänkar vid västra Lappkärret",
  //     location: {
  //       coordinates: [59.3689071, 18.0672525],
  //     },
  //     noRatings: 1,
  //     averageRating: 4.2,
  //   },
  // });

  const locations = await prisma.location.findMany({ take: 10 });

  console.log(locations);

  return {
    props: { locations: JSON.parse(JSON.stringify(locations)) },
  };
};

export default Home;
