import Layout from "components/Layout";
import prisma from "lib/prisma";
import Users from "modules/Users";
import { User } from "modules/Users/types";
import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

// export const UserContext = React.createContext<{
//   user: User;
// }>({
//   user: {
//     id: "",
//     role: "USER",
//     name: "",
//     image: "",
//     email: "",
//     emailVerified: new Date(),
//     dateCreated: new Date(),
//     reviews: [],
//     locationsAdded: [],
//   },
// });

const UserPage: NextPage = ({ usrs }: any) => {
  const [users, setUsers] = useState<User[]>(usrs as User[]);

  return (
    <>
      <Head>
        <title>Parkerad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Users users={users} />
      </Layout>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const users = await prisma.user.findMany({
    include: {
      locationsAdded: {},
      reviews: {},
    },
  });

  return {
    props: { usrs: JSON.parse(JSON.stringify(users)) },
  };
};

export default UserPage;
